[tool.poetry]
name = "msys2-web"
version = "0.1.0"
description = ""
authors = ["Christoph Reiter <reiter.christoph@gmail.com>"]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
httpx = {extras = ["http2"], version = "^0.27.0"}
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
jinja2 = "^3.1.2"
fastapi-etag = "^0.4.0"
gunicorn = "^22.0.0"
aiolimiter = "^1.0.0-beta.1"
pydantic = "^2.0.3"
zstandard = "^0.22.0"
MarkupSafe = "^2.1.1"
uvicorn-worker = "^0.2.0"

[tool.poetry.group.dev.dependencies]
reuse = "^4.0.3"
mypy = "1.10.1"
flake8 = "^7.0.0"
pytest = "^8.0.0"
requests = "^2.23.0"
respx = "^0.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
